### ISSUE TITLE
Navigation missing on mobile

### ISSUE THREAD

**Issue by CherryDT** [GeekyAnts/sb-admin-svelte#11]
I don't see any way to open the sidebar on mobile (no hamburger button). Neither in landscape nor portrait mode. 

![Screenshot_2020-03-07-11-55-43-72](https://user-images.githubusercontent.com/6010463/76141210-b5232280-606a-11ea-8dfd-cb59de07970e.png)
![Screenshot_2020-03-07-11-55-32-23](https://user-images.githubusercontent.com/6010463/76141211-b6544f80-606a-11ea-8b15-69074b064194.png)

**Comment by Srishti-Sharma** [comment]
This has been fixed with PR [#12](https://github.com/GeekyAnts/sb-admin-svelte/pull/12)
